### ISSUE TITLE
compatable with pytorch 0.3.1?

### ISSUE THREAD

**Issue by arendu-zz** [rusty1s/pytorch_unique#5]
Hi, I tried to install `pytorch_unique` by cloning this repo and running `python setup.py install` but I get the following error:

```
Traceback (most recent call last):
  File "setup.py", line 3, in <module>
    from torch.utils.cpp_extension import BuildExtension, CUDAExtension
ModuleNotFoundError: No module named 'torch.utils.cpp_extension'
```
It looks like `torch.utils.cpp_extension` is only available in pytorch 0.4, does this mean I can not use it with pytorch 0.3.1?

**Comment by rusty1s** [comment]
Please try version 0.3.1.

**Comment by arendu-zz** [comment]
That's what I am using.
```
Python 3.6.4 |Anaconda, Inc.| (default, Jan 16 2018, 18:10:19)
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.__version__
'0.3.1'
>>> from torch.utils.cpp_extension import BuildExtension, CUDAExtension
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'torch.utils.cpp_extension'
```

**Comment by rusty1s** [comment]
No, torch-unique 0.3.1 :)

**Comment by arendu-zz** [comment]
Ha! ok it seems to have installed fine, but I get a different error when I try to import

```
>>> import torch
>>> from torch_unique import unique_by_key
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/export/b07/arenduc1/pytorch_unique_0.3.1/torch_unique/__init__.py", line 1, in <module>
    from .unique import unique
  File "/export/b07/arenduc1/pytorch_unique_0.3.1/torch_unique/unique.py", line 4, in <module>
    from .utils.ffi import get_func
  File "/export/b07/arenduc1/pytorch_unique_0.3.1/torch_unique/utils/ffi.py", line 1, in <module>
    from .._ext import ffi
  File "/export/b07/arenduc1/pytorch_unique_0.3.1/torch_unique/_ext/ffi/__init__.py", line 3, in <module>
    from ._ffi import lib as _lib, ffi as _ffi
ModuleNotFoundError: No module named 'torch_unique._ext.ffi._ffi'
>>> from torch_unique import unique
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/export/b07/arenduc1/pytorch_unique_0.3.1/torch_unique/__init__.py", line 1, in <module>
    from .unique import unique
  File "/export/b07/arenduc1/pytorch_unique_0.3.1/torch_unique/unique.py", line 4, in <module>
    from .utils.ffi import get_func
  File "/export/b07/arenduc1/pytorch_unique_0.3.1/torch_unique/utils/ffi.py", line 1, in <module>
    from .._ext import ffi
  File "/export/b07/arenduc1/pytorch_unique_0.3.1/torch_unique/_ext/ffi/__init__.py", line 3, in <module>
    from ._ffi import lib as _lib, ffi as _ffi
ModuleNotFoundError: No module named 'torch_unique._ext.ffi._ffi'
```
I have also done `pip install cffi`

**Comment by rusty1s** [comment]
Hi! Can you show me the error log when you clone the repository and run python setup.py install?

**Comment by rusty1s** [comment]
Closed due to inactivity.
